/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Picture } from "./picture";
export namespace Components {
    interface MyCard {
        "picture": Picture;
    }
    interface MyGrid {
    }
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyGridElement extends Components.MyGrid, HTMLStencilElement {
    }
    var HTMLMyGridElement: {
        prototype: HTMLMyGridElement;
        new (): HTMLMyGridElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-grid": HTMLMyGridElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "picture"?: Picture;
    }
    interface MyGrid {
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-grid": MyGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-grid": LocalJSX.MyGrid & JSXBase.HTMLAttributes<HTMLMyGridElement>;
        }
    }
}
